name: cons_app
description: An app to report problems in India
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.10.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.2.0
  google_sign_in: ^6.2.1
  location: ^5.0.1
  image_picker: ^2.1.0
  firebase_storage: ^11.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
